// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT7A7KKaKnhVULyxRpY82hvv_2gro3NdE',
    appId: '1:296535717159:web:cb0c211c599cbb388aa502',
    messagingSenderId: '296535717159',
    projectId: 'chat-app-c82f6',
    authDomain: 'chat-app-c82f6.firebaseapp.com',
    storageBucket: 'chat-app-c82f6.appspot.com',
    measurementId: 'G-0B08LZD2F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCE8iYCF1h5WqBja08DnEKIcdxqZECCe4',
    appId: '1:296535717159:android:304e7dde643b00b68aa502',
    messagingSenderId: '296535717159',
    projectId: 'chat-app-c82f6',
    storageBucket: 'chat-app-c82f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-xsGx-gqu0gTohPlbEws8ySUMuRExNU',
    appId: '1:296535717159:ios:e5bc1baee532941e8aa502',
    messagingSenderId: '296535717159',
    projectId: 'chat-app-c82f6',
    storageBucket: 'chat-app-c82f6.appspot.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-xsGx-gqu0gTohPlbEws8ySUMuRExNU',
    appId: '1:296535717159:ios:e5bc1baee532941e8aa502',
    messagingSenderId: '296535717159',
    projectId: 'chat-app-c82f6',
    storageBucket: 'chat-app-c82f6.appspot.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT7A7KKaKnhVULyxRpY82hvv_2gro3NdE',
    appId: '1:296535717159:web:4cb4eb8bec37dc3b8aa502',
    messagingSenderId: '296535717159',
    projectId: 'chat-app-c82f6',
    authDomain: 'chat-app-c82f6.firebaseapp.com',
    storageBucket: 'chat-app-c82f6.appspot.com',
    measurementId: 'G-HLCD61K9KB',
  );

}